apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
    host: ripley
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: backend
        host: ripley
    spec:
      containers:
      - name: backend
        image: 250359480282.dkr.ecr.us-east-1.amazonaws.com/backend:latest
      nodeSelector:
        host: ripley
