apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
  selfLink: /api/v1/namespaces/default/services/grafana
  annotations:
    
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:573624488707:certificate/4fb1a4ae-ce9c-462a-8c9e-020f86323292
    
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
  sessionAffinity: None
  type: LoadBalancer
  selector:
    app: grafana
