FROM node:latest as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
 
COPY package.json ./
COPY package-lock.json ./

RUN npm install --silent

COPY . ./

RUN npx @angular/cli build

FROM nginx:stable-alpine

COPY --from=build /app/dist/frontend-angular /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]