FROM node:12.18.1
 
WORKDIR /app
 
COPY package.json package.json
COPY package-lock.json package-lock.json
 
RUN npm install
 
COPY . .

RUN npm install pm2 -g
ENV PM2_PUBLIC_KEY nuvawl5dsilbsl0
ENV PM2_SECRET_KEY 4h4wyn1neym6ka3

expose 4502

ENV enviroment qa

CMD ["pm2-runtime", "server.js"]
# CMD ["npm", "run", "start:qa"]