service: inversiones

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain: 
    domainName: service.nagaroth.net
    basePath: ${opt:stage, self:provider.stage}
    stage: ${opt:stage, self:provider.stage}
    endpointType: 'regional'
    createRoute53Record: true
    autoDomain: true
    certificateArn: arn:aws:acm:${opt:region, self:custom.region}:250359480282:certificate/03cf3269-6cf5-4aa4-9840-de4621755464

  serverless-offline:   
    httpPort: 4000
    websocketPort: 4004
    lambdaPort: 4005
  
  webpack:
    webpackConfig: './webpack.config.js'
    packager: 'npm'
    excludeFiles: src/**/*.test.js
    mode: 'development'
    includeModules:
      packagePath: './package.json'
      
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, "us-east-1"}
  prefix: ${self:custom.stage}-${self:service}

  arnIam: "arn:aws:iam::*:role/${self:custom.prefix}-${self:custom.region}-role"

  configuracion:
    dev:
      STAGE: ${self:custom.stage}
      REGION: ${self:custom.region}
      API_BOLSA_SANTIAGO: https://startup.bolsadesantiago.com/api/consulta/
      TOKEN_BOLSA_SANTIAGO: 158516D931F24DC894F237DCF4B21EE8
      MAX_REQUEST_X_DIA: 50
      DB_USER: "root"
      DB_PASS: ""
      DB_HOST: "localhost"
      DB_PORT: 3306
    prod:
      STAGE: ${self:custom.stage}
      REGION: ${self:custom.region}
      API_BOLSA_SANTIAGO: https://startup.bolsadesantiago.com/api/consulta/
      TOKEN_BOLSA_SANTIAGO: 158516D931F24DC894F237DCF4B21EE8
      MAX_REQUEST_X_DIA: 50
      DB_USER: "root"
      DB_PASS: ""
      DB_HOST: "localhost"
      DB_PORT: 3306
  
  deletionPolicy:
    default: Delete
    dev: Delete
    prod: Retain
  updateReplacePolicy:
    default: Delete
    dev: Retain
    prod: Retain

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  stackTags:
    Responsable: "Gerardo"
    Version: "0.0.1"
    Funcionalidad: "Rol kubernetes"
    Criticidad: "Alta"
  environment: ${self:custom.configuracion.${self:custom.stage}, self:custom.configuracion.dev}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - iam:DeleteRole
            - iam:DeleteRolePolicy
          Resource:
            - ${self:custom.arnIam}

functions:
  crearUsuario:
    handler: src/index.crearUsuario
    timeout: 20
    events:
      - http: 
          path: /crearUsuario
          method: POST
          cors: true
  actualizarUsuario:
    handler: src/index.actualizarUsuario
    timeout: 20
    events:
      - http: 
          path: /actualizarUsuario
          method: POST
          cors: true
  obtenerUsuariosDisponibles:
    handler: src/index.obtenerUsuariosDisponibles
    timeout: 20
    events:
      - http: 
          path: /obtenerUsuariosDisponibles
          method: POST
          cors: true
  compararInversiones:
    handler: src/index.compararInversiones
    timeout: 20
    events:
      - http: 
          path: /compararInversiones
          method: POST
          cors: true
  
  obtenerInversiones:
    handler: src/index.obtenerInversiones
    timeout: 20
    events:
      - http: 
          path: /obtenerInversiones
          method: POST
          cors: true
  invertir:
    handler: src/index.invertir
    timeout: 20
    events:
      - http: 
          path: /invertir
          method: POST
          cors: true
  actualizarInversion:
    handler: src/index.actualizarInversion
    timeout: 20
    events:
      - http: 
          path: /actualizarInversion
          method: POST
          cors: true
  obtenerEstadoInversion:
    handler: src/index.obtenerEstadoInversion
    timeout: 20
    events:
      - http: 
          path: /obtenerEstadoInversion
          method: POST
          cors: true
  estadoInversiones:
    handler: src/index.estadoInversiones
    timeout: 20
    events:
      - http: 
          path: /estadoInversiones
          method: POST
          cors: true
  estadoGlobalInversiones:
    handler: src/index.estadoGlobalInversiones
    timeout: 20
    events:
      - http: 
          path: /estadoGlobalInversiones
          method: POST
          cors: true

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - node_modules/**