# build.yml
on:
  push:
    branches:
      - master

name: CI/CD QA

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  ENVIROMENTFILE: ${{ secrets.ENVIROMENT }}
  REGION: ${{ secrets.REGION }}
  PROJECT: backend
  CONTAINER_IMAGE: backend:${{ github.sha }}
  
jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout 🛎️
      uses: actions/checkout@master